# Generated by Django 5.2 on 2026-02-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='imgage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
