# Generated by Django 6.0 on 2026-02-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0002_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='main_video.section'),
        ),
    ]
