# Generated by Django 6.0 on 2026-02-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0003_alter_quiz_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='main_video.section'),
        ),
    ]
