# Generated by Django 6.0 on 2026-02-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0005_alter_quizresult_unique_together_alter_quiz_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='main_video.section'),
        ),
    ]
